apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo.fullname" . }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "echo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pipeline_agent
          image: {{ .Values.pipeline_agent.image.name }}
          imagePullPolicy: {{ .Values.pipeline_agent.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /ready
              port: http
            failureThreshold: 6
            periodSeconds: 10
          resources:
            {{- toYaml .Values.pipeline_agent.resources | nindent 12 }}
        - name: executor-echo
          image: {{ .Values.executor_echo.image.name }}
          imagePullPolicy: {{ .Values.executor_echo.image.pullPolicy }}
          resources:
            {{- toYaml .Values.executor_echo.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}