replicaCount: 1

pipeline_agent:
  image:
    name: aryazanov/pipeline-agent
    tag: 0.0.1
    containerRegister: docker.io
  imageConfig:
    pullPolicy: Always
  env:
    - name: PIPELINE_AGENT__NAME
      value: "EchoAgent"
    - name: PIPELINE_AGENT__EXECUTORS__0__NAME
      value: "echo1"
    - name: PIPELINE_AGENT__EXECUTORS__0__TARGET
      value: "127.0.0.1:50051"
    - name: PIPELINE_AGENT__EXECUTORS__1__NAME
      value: "echo2"
    - name: PIPELINE_AGENT__EXECUTORS__1__TARGET
      value: "127.0.0.1:50052"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

executor_echo_1:
  image:
    name: aryazanov/example-echo
    tag: 0.0.1
    containerRegister: docker.io
  imageConfig:
    pullPolicy: Always
  env:
    - name: COMMAND_EXECUTOR_NAME
      value: "echo1"
    - name: COMMAND_EXECUTOR_SERVER_GRPC_PORT
      value: ":50051"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

executor_echo_2:
  image:
    name: aryazanov/example-echo
    tag: 0.0.1
    containerRegister: docker.io
  imageConfig:
    pullPolicy: Always
  env:
    - name: COMMAND_EXECUTOR_NAME
      value: "echo2"
    - name: COMMAND_EXECUTOR_SERVER_GRPC_PORT
      value: ":50052"
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

nodeSelector:
  kubernetes.io/os: linux