replicaCount: 1

pipeline_agent:
  image:
    name: docker.io/aryazanov/pipeline-agent:0.0.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

executor_echo:
  image:
    name: docker.io/aryazanov/example-echo:0.0.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

nodeSelector:
  kubernetes.io/os: linux